### PR TITLE
1907-04-04

### PR DESCRIPTION
**Pull request by stevensaxt**

### CODE REVIEW

**Comment by huoyanzhizhou** [comment]
Please check the dates and measures in 195-10-20. For example, the dates in MOUVEMENT MARITIME DU PORT D’ALEXANDRIE (page 4) is not updated.

**Comment by whanley** [comment]
Hi Steven, There are two files here for your deliverables: 1907-04-04 and 1907-04-04.1. Please put all your changes in 1907-04-04.xml, delete 04.1, and send a new pull request.

Also, as Weber, suggested, look at https://dig-eg-gaz.github.io/how-to/digitization/polished-tei-instructions/#1-get-the-page-hierarchy-right

**Comment by huoyanzhizhou** [comment]
Please delete the incorrect files.

**Comment by stevensaxt** [comment]
Hi! I thought I deleted the file and replaced it with the correct one but I
guess I did not do so correctly. How can I make sure the file in question
is deleted for good so I can upload the correct one?

Thank you!

Steven Saxton

**Comment by huoyanzhizhou** [comment]
You should go to your forked repository and delete the wrong file both online on Github and offline in your cloned folder.

**Comment by stevensaxt** [comment]
That worked! Thank you so much for your help! My other question is about
the assignment due tonight. I was not feeling well Thursday and was
wondering if the assignment was covered then? I'm just not sure what's due.
Thank you so much again for all of your continued help!

Steven Saxton

**Comment by huoyanzhizhou** [comment]
The assignment should be using Xpath query to search the whole repository to find out results for the topics that interest you. Then you should copy them into Atom and make up a sheet using Regular Expression. After than, you should be able to use them in Tableau to create a visualization. Please check our How-To page https://dig-eg-gaz.github.io/how-to/ 9, 11, 12, 13 for details about how to do this. I will copy Dr. Hanley here @whanley if there is more to add.

**Comment by whanley** [comment]
Great job getting your files sorted out--looks good now.

Your deliverables need more work. At this point, the main things are:
- getting page hierarchy right (https://dig-eg-gaz.github.io/how-to/digitization/polished-tei-instructions/)
- indicate paragraphs. It looks like you might have pasted into the text mode, rather than the author mode? Ask for some help if you need it.
- update tables from the template versions.

Also, please complete the work on your verification.

**Comment by whanley** [comment]
Thanks for your continued work. Please look at earlier comments. Also, this is the wrong spot for the blog post. Look at the instructions about submitting blog posts: they need to be in the blog-post repository.

**Pull request merged**
