### PR TITLE
1907-06-17

### PR DESCRIPTION
**Pull request by laneydegroat**
Deliverable 2 and 3

### CODE REVIEW

**Comment by whanley** [comment]
Great work. I'll give you the marks, but please make these small corrections before I merge the file into the master repository.

Deliverable 2 complete! But:
Page 2
line 1895: this date should go in previous item. Following line (THE KHEDIVE AND HIS CRITICS) should be the headline.
Page 3
Break local and general down into items, each with own head.

Deliverable 3 I'll call complete as well. But:
Page 4
There's a template for cheap prepaid advertisements: https://dig-eg-gaz.github.io/templates/#cheap-prepaid-advertisements. Also for Bourse Khediviale: https://dig-eg-gaz.github.io/templates/#bourse-khediviale

Page 6
Line 5758 close div
Line 5815 close div

**Comment by whanley** [comment]
@laneydegroat have you made these changes to the Monday issue?

**Comment by laneydegroat** [comment]
Yes, I made the changes. Did you want me to submit it again?

**Comment by whanley** [comment]
Yes please

**Pull request closed without merging**
