### PR TITLE
deliverable 2 pgs 2 and 3

### PR DESCRIPTION
**Pull request by gam18g**

### CODE REVIEW

**Comment by huoyanzhizhou** [comment]
Please create page div for each page and create section div with features. For example, "Local and General" should be a section with a feature equals to "local". Please check the feature page on our website for more information. See: https://dig-eg-gaz.github.io/contents/features/

**Comment by whanley** [comment]
Good start Gabi. Don't hesitate to come by office hours for help. Keep at it!

**Comment by huoyanzhizhou** [comment]
Any updates?

**Comment by whanley** [comment]
Now working on a different week, so closing this pull request.

**Pull request closed without merging**
