### PR TITLE
deliverable 4, tuesday 1-6

### PR DESCRIPTION
**Pull request by gretchensandorf**
full tuesday issue

### CODE REVIEW

**Comment by gretchensandorf** [comment]
deliverable 4

**Comment by whanley** [comment]
Dear @gretchensandorf -- please delete all of the jpg files from your fork of the content folder, leaving just the xml file, then resend the pull request.

**Comment by gretchensandorf** [comment]
Good Morning Mr. Hanley,
My computer broke on Tuesday and has been in the bookstore ever since. I borrowed a computer from Dirac and you are not allowed to download software on it (oxygen or ocr). I have not been able to work on the assignments because of this. I guess if you were allowed to download software on the borrowed computers then everyone would do it. Either way, please let me know what I should do. 

Very Respectfully,

//SIGNED//

C/3c Gretchen Sandorf

145th AFROTC Cadet Wing

Florida State University

**Comment by whanley** [comment]
Hi @gretchensandorf this looks good--but please remove your blog post and image--they should be in a fork of the blog-post repository, not here. Check the blogging instructions.

**Comment by whanley** [comment]
Hi @gretchensandorf -- the pull request is good as far as the xml issue files are concerned, but please move your blog post and image out (and into the [blog posts repository](https://github.com/dig-eg-gaz/blog-posts)) and then update the pull request.

**Comment by whanley** [comment]
@gretchensandorf I've done this for you now--but I wish you'd done it yourself!

**Pull request merged**
