### PR TITLE
Update 1907-06-03.xml

### PR DESCRIPTION
**Pull request by BaileeKu**
creating pg. 2-3 of day 1, minor edits to pg. 1

### CODE REVIEW

**Comment by BaileeKu** [comment]
Sign of life

**Comment by BaileeKu** [comment]
Sign of life/deliverable 3

**Comment by whanley** [comment]
You're doing good work, but have cleaning to do--much of it you've noted in comments. One thing:
- line 2061, add a `</div>` tag to close page 2 before you start page 3.
I'll help you get rid of the changes you made to 1905 files in your repo. Ask me in class.

**Comment by BaileeKu** [comment]
I will submit something for my blog post deliverable tomorrow- sign of life

**Comment by whanley** [comment]
Hi Bailee. Lots of good work here. I especially like how careful you are being about using comments. That's really helpful.

It looks like OCR is causing you a lot of trouble. Have you tried the Google Drive approach?

Maybe it would be worth going back to one of your early issues and tuning it up now? Having something complete might be satisfying. But if you have found a good working groove doing what you're doing, keep at it.

You're always welcome at office hours to look over stuff with us.

**Comment by BaileeKu** [comment]
I have yet to try Google Drive, but I probably will end up using it on pages that aren't too crooked.

**Comment by huoyanzhizhou** [comment]
Any news?

**Comment by BaileeKu** [comment]
Any news on what?

**Comment by huoyanzhizhou** [comment]
I mean "any update?" Just keep updating, thanks.

**Comment by whanley** [comment]
Bailee let's sit down and go over the pull request next week.

**Comment by whanley** [comment]
Bailee, I've entered these changes manually. Your first four issues of your week, as well as the three stocks and shares tables you changed, are now in the master repository.

**Comment by BaileeKu** [comment]
Which pull request do you want to go over?

**Pull request closed without merging**
