### PR TITLE
August 1st 1905 Verification/Celine Benedico

### PR DESCRIPTION
**Pull request by celinebenedico**
There were no major issues whatsoever, I mainly just changed small issues like headers in the wrong places, and some small texts missing. Also, minimal spelling errors, and wrong numbers in data.

### CODE REVIEW

**Comment by whanley** [comment]
You submitted 2 files: 1905-01-08 and 1905-08-01. I'm not sure which contains the work you wanted to do. Make sure that your work is in the 1905-08-01, delete the other file, and resubmit.

**Comment by celinebenedico** [comment]
I believe I resubmitted it in the correct file name, sorry for the confusion! Please let me know if I need to resubmit it again!

**Comment by whanley** [comment]
Thanks, the file is good now.

A few things:
- title on line 1900 should be in following item
- add wire report divs to column one of page 3
- correct date line 7267, 7598, elsewhere?

**Comment by celinebenedico** [comment]
Hi! I believe I fixed all the errors! Please let me know if there is more I need to change for the full grade.

**Comment by celinebenedico** [comment]
I'm unsure if you received my deliverable but I uploaded it! I was unable to do page number one because it wouldn't translate into google docs, is there any advice you have for that issue? Let me know if you received it, thank you!!

**Comment by huoyanzhizhou** [comment]
Please delete your incorrect file "Deliverable 2".

**Comment by whanley** [comment]
Great work Celine but there are some basic things to sort out before we can look carefully. The 1907-01-14.xml file needs to be completed--make sure that it contains all six pages. Delete the file named "Deliverable 2".  Fix the contents of the headers of both 01-14 and 01-15. Ask for help if you don't know what they should contain, but it should be pretty logical--just delete the dates that don't apply to the work you've done. Add the `@feature` attribute to divs were necessary.

Complete your issue verification.

**Comment by whanley** [comment]
See my last comment please.

**Pull request merged**
