### PR TITLE
Deliverable 1 Resubmission

### PR DESCRIPTION
**Pull request by 19peytonsmith**

### CODE REVIEW

**Comment by huoyanzhizhou** [comment]
Good job. One small issue: Please put your page 1 ads inside the page 1 div: '<div type="page" n="1"></div>'

**Comment by whanley** [comment]
Yes. Specifically, the `</div>` on line 34 should be on line 1592.

**Comment by 19peytonsmith** [comment]
Gotcha, now, is there a way I can resubmit the file with that correction? Or is it best to apply the correction into my Deliverable 2?

**Comment by whanley** [comment]
Merge in the change as you add deliverable 2. All your Monday work will be in a single file.

**Comment by whanley** [comment]
I'm closing this pull request, because you've got better work in another pull request.

**Pull request closed without merging**
