### PR TITLE
Create 1907-12-23

### PR DESCRIPTION
**Pull request by mitchreynolds**

### CODE REVIEW

**Comment by whanley** [comment]
You deleted the file you meant to add--this pull request is empty. Add the file back into your branch of the content repository and send another pull request.

**Comment by whanley** [comment]
Generally it looks like OCR is working. Good! 
- use the "section" attribute wherever you can. They are listed here: https://dig-eg-gaz.github.io/contents/features/
- line 1579, add another `</div>` to close page 1 before you start page 2.
- when you comment about missing templates and ads, give the name of what's missing.

Keep at it!

**Comment by whanley** [comment]
Hi Mitch,

Your Monday issue is pretty complete, but needs to be tidied up. Take a look at this tutorial on pages and breaks: https://dig-eg-gaz.github.io/how-to/digitization/polished-tei-instructions/

Have you had better luck with OCR using methods other than tesseract?

Make sure you update the templates and ads to match the content of your issue.

Tuesday is a good start. Keep at it!

**Comment by mitchreynolds** [comment]
Cisdem for OSX seems to be doing a good enough job, but it has trouble reading text on page areas that are bright with fainter text.

**Comment by huoyanzhizhou** [comment]
Any recent news?

**Pull request merged**
