### PR TITLE
1907-07-15 again

### PR DESCRIPTION
**Pull request by PCN19**

### CODE REVIEW

**Comment by whanley** [comment]
I'm looking for more content before I can dig into this file.

**Comment by PCN19** [comment]
I think I'll come in for more help. I should be understanding this more, but I'm still not getting how to use OCR, as in converting the picture to text. I think editing will be easier after that, since I understand Atom more, and the other is just using templates.
________________________________

**Comment by PCN19** [comment]
Okay! I'm seeing Weber today to see if he can help me first, though.
________________________________

**Comment by whanley** [comment]
Any updates?

**Comment by PCN19** [comment]
Not much but I do want To go to your office hours next week.
________________________________

**Comment by PCN19** [comment]
Mr. Hanley,

I wanted to be honest and say that I'm struggling quite a bit in school, which is why I'm so behind here. I've asked where to get help from my adviser so I hope to be doing better! I don't want to put off working at this so I'll be sure to find a way to come see you this week. If not, I'd like to keep emailing.
________________________________

**Comment by huoyanzhizhou** [comment]
Any news? If you have any problems, please let us know so we can work on them together.

**Comment by whanley** [comment]
See you this week I hope!

**Pull request merged**
