### PR TITLE
Deliverable 3; Update 1907-10-14.xml

### PR DESCRIPTION
**Pull request by 19peytonsmith**

### CODE REVIEW

**Comment by 19peytonsmith** [comment]
Not sure why it added on to this pull request instead of making a new one, anyways, the last one is the Monday issue in its entirety for Deliverable 3.

**Comment by whanley** [comment]
This looks really good. Please add the appropriate `feature` tags (info here https://dig-eg-gaz.github.io/contents/features/) and put items into sections (e.g. in the local section) where appropriate. But this is nice work and I'll call it complete.

**Comment by 19peytonsmith** [comment]
There you go, my re-submission with the appropriate feature tags in my divs also changed some of the "item" divs into "section" divs as you requested. I noticed I missed an advertisement on the first page so I double-checked to see if I missed anything else, and I didn't. Also, the divs--whether that be an advert or an item-- without an xml:id are ones that I wrote entirely by myself if you wonder why some have no id's.

**Comment by 19peytonsmith** [comment]
Did a minor fix on the dates in the Telegrams section utilizing <dateline> </dateline>.

**Comment by whanley** [comment]
Very nice. I'll mark this complete.

I think you could still update some french templates, even if the language isn't clear to you. They are numeric and formulaic. Find them by doing a `//@when` search--the dates in 1905 and 1906 are in divs to be updated.

**Pull request merged**
