### PR TITLE
Create 1907-12-02.xml

### PR DESCRIPTION
**Pull request by VFaynberg**
Page one of Deliverable 1

### CODE REVIEW

**Comment by VFaynberg** [comment]
Deliverable 2

**Comment by VFaynberg** [comment]
Also when it came to the missing ads, I just commented on my original document on the ads that I couldn't find in the website and had to type in all the information and measures manually.

**Comment by VFaynberg** [comment]
Deliverable 3

**Comment by whanley** [comment]
This looks really good, Victor. Two things for now: 
- Your pull request should only contain 1 file, named 1907-12-02.xml. Put all your deliverables there (i.e. rename the file named v.2), delete all other files, and send a new pull request.
- make sure your page 1 div closes at the end of page 1, and do the same with the other pages.

**Comment by whanley** [comment]
Victor--deliverables 1 and 3 look good. 2 needs a bit more work. Specifically, I want you to use the feature attribute properly. For example, the local and general section should have this tag: `<div type="section" feature="local">`. You have lots of `<div type="nameplate">` tags--this is not correct--only use this on the top of the 1st page.

Your Tuesday issue is coming along, but is missing some pages.

**Comment by VFaynberg** [comment]
I Still have to fix all the divtype: features on these and finish Saturday's issue

**Comment by huoyanzhizhou** [comment]
Oh, you submit a lot at once. Overall great job. It seems that you know exactly what to do in the next step, so maybe we can merge this @whanley. Just remember to update your files!

**Comment by whanley** [comment]
Merging. But Thursday and Saturday are mostly empty. Keep at it!

**Comment by whanley** [comment]
We can sit down and tidy up much of this stuff quite quickly. Good work generally, but polish required--and some content left to add.

**Pull request merged**
