### PR TITLE
Changes in issues 1906-(18-20)

### PR DESCRIPTION
**Pull request by SamuelPagan**
Deleted some text that was not in the original issue, changed some dates to match with the issue, and added some comments for some pages that were missing entire sections.

### CODE REVIEW

**Comment by whanley** [comment]
There is a problem with your file name: it should be -09-, not just -9-. As a result of the incorrect name, this file will not replace the existing file in the repository. Please rename and resubmit.

Also, please get missing templates from the repository and insert them where needed.

**Comment by SamuelPagan** [comment]
I uploaded the first three pages of my first date which is October 18 1906 I have not finished changing the templates but I would like to do that and fix the other issue over the next week.

**Comment by SamuelPagan** [comment]
Added pages 4-6 of 1906-10-18

**Comment by huoyanzhizhou** [comment]
Please delete 1905-9-28.xml. 
Lots of good work here. However, remember to divide your OCR text into sections contains small items. Also, please use features, see: https://dig-eg-gaz.github.io/contents/features/

**Comment by whanley** [comment]
I've removed the incorrectly named verification. Please add divs and paragraphs etc to the OCRed text you provided for the correctly named verification.

Thanks for the deliverables--keep working on them!

**Comment by whanley** [comment]
Paragraphs are lacking in your new OCR.

**Comment by whanley** [comment]
The October 20 issue needs paragraph breaks. Paste the OCR into the author mode, not the text mode. Also, the header needs to be filled with accurate information.

**Comment by SamuelPagan** [comment]
Put more p brackets in the OCR

**Comment by huoyanzhizhou** [comment]
Please add more features, see https://dig-eg-gaz.github.io/contents/features/
Many dates need to be updated, even the teiheader dates.

**Comment by whanley** [comment]
You've got almost all the content together--great job! Please don't use type="article" for divs, except when there's an author. Use div type="item" as a default. Also, don't use the `<note>` tag. Make each item its own `<div>`, with its own `<head>`.

**Comment by SamuelPagan** [comment]
Changed the type=article to type=item and removed the <note> tag that was in there please let me know if there are any other changes that need to be done.

**Comment by whanley** [comment]
Please check the teiHeader of all of your files to make sure that the information is correct.

Where you've done OCR (for instance on page 3), make sure that your text is divided into a div for each item, not just one per column.

Otherwise this is complete.

**Comment by SamuelPagan** [comment]
Added headers to the OCR, created separate divs for each article within the columns and fixed the teiHeader for all pages. Please let me know if this is alright.

**Comment by whanley** [comment]
Yes. Good job, now complete.

**Pull request merged**
