### PR TITLE
1905-08-29

### PR DESCRIPTION
**Pull request by jah18h**
Problems mainly on first few pages. Made a number of additions and corrections.

### CODE REVIEW

**Comment by huoyanzhizhou** [comment]
The measures in REUTER'S TELEGRAMS (page 6) are not updated.

**Comment by jah18h** [comment]
Updated 6th page

**Comment by whanley** [comment]
The when= attribute on certain date tags is incorrect.

**Comment by jah18h** [comment]
Need help with OCR or need to rescan my microfilm for 1907-09-30

**Comment by whanley** [comment]
James, ask us for help with OCR. What seems to be going wrong?

**Comment by whanley** [comment]
Any new work to report?

**Pull request merged**
