### PR TITLE
Comments on 1905-09-26

### PR DESCRIPTION
**Pull request by Isanze526**
Comments were made about this file regarding errors.

### CODE REVIEW

**Comment by whanley** [comment]
Good work finding the deficiencies. Now could you please proceed to find the missing items in the repositories and drop them in place?

**Comment by Isanze526** [comment]
I learned it is quite difficult to modify my scans to use OCR. I got through the first 2 pages but page 3 was difficult. I'll be sure to finish up before next class.

**Comment by whanley** [comment]
The first thing to address with deliverables 1 and 2 is your divs. You use ` <div type="page">`  all over the place, for things that should be items. Also, look at this: https://dig-eg-gaz.github.io/how-to/digitization/polished-tei-instructions/

**Comment by whanley** [comment]
Your Tuesday issue looks quite good--keep at it. You're using div type="wireReport" in some places where you should use "item"--only use wireReport for Havas and Reuters telegrams. 

Also, go back to your Monday issue and change the div type from page to section or item for lots of the divs.

**Pull request merged**
