### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by krr17c**
krr17c

### CODE REVIEW

**Comment by whanley** [comment]
Hi Karl. Rename this file 1907-12-16.xml and send a new pull request.

**Comment by krr17c** [comment]
I changed it now. However, I have a question. Every time I try to create a
new pull request for the page 2 and 3 issues, it either says the file is
too large or it brings me to the first page pull request.

**Comment by whanley** [comment]
Hi Karl. All of these pages need to be combined into a single file, named 1907-12-16.xml. Put this file in your content repository, delete the -p1 -p2 etc files, and send a new pull request.

**Comment by whanley** [comment]
Hi Karl. You've done a nice job getting so much material into these two issues. These things need work:
- Your Monday file is correctly named. Your Tuesday file needs to be named 1907-12-17.xml. The other files (with page numbers in the filename) need to be deleted.
- Your page structure is not correct. Look at this tutorial: https://dig-eg-gaz.github.io/how-to/digitization/polished-tei-instructions/
- Much of your OCRed material is not divided into items, headlines, and paragraphs
- Templates and ads need to be updated to reflect the contents of _your_ issue.
Keep at it!

**Comment by huoyanzhizhou** [comment]
Any news?

**Comment by krr17c** [comment]
Yes I have been busy with classes these past few weeks, but I will be
coming to class and office hours today to try to finish my xpath query and
anything else I am behind on. I will continue to work on the deliverables
as the week progresses. Thank you for your patience.

**Comment by whanley** [comment]
Great to see so many files. I'm just starting to look through them. It seems that some of your OCR on page 3 is incomplete? There are divs with only a headline and no text?

**Comment by krr17c** [comment]
I see, so page three has empty text put into it. I believe that was due to
unusable ocr. I place a comment on it that the OCR was unusable, however, I
will check again just to make sure.

**Pull request merged**
