### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by marilarosa4**
Most articles correct, some advertisement out of order.

### CODE REVIEW

**Comment by whanley** [comment]
Good start but there are still lots of things to be done.

The templates on pages 4 and 6 do on correspond to the figures in the issue.

On page 5, can you add paragraph breaks?

**Comment by marilarosa4** [comment]
Still have some editing to correct OCR, will continue over the next few days

**Comment by whanley** [comment]
Great start! A few things: make sure that the type and feature attributes for your divs are correct. Add paragraphs etc (as you've done in page 3). And use templates for a great deal of page 5!

**Comment by huoyanzhizhou** [comment]
Good effort. Please use more features and add more cb and cols. see: https://dig-eg-gaz.github.io/contents/features/

**Comment by whanley** [comment]
There are still some article that need to be broken out into their own divisions, and there's material missing. Keep at it, and ask us for help!

**Pull request merged**
