### PR TITLE
1905-09-12 Robert Klein

### PR DESCRIPTION
**Pull request by skylartheswimmer**
Made minor changes to some texts.
Filled in templates that were missing or incorrect.
Some sections I could not find for the missing templates.

### CODE REVIEW

**Comment by huoyanzhizhou** [comment]
You seems to only focus on the first page. There are still many other things could do
: For example, Line 2619 Stocks and Shares should be a table, using the template on our website: https://dig-eg-gaz.github.io/contents/templates/#stocks-shares-and-finance

**Comment by skylartheswimmer** [comment]
Second revision of the 1905-09-12. Corrected as much as possible on the third page, and surprisingly a lot of the third page was done. However, I could not find a template for a lot of the charts in the last column so I manually typed out the first one, which I think turned out surprisingly well. There are a few other ones in the same column, but it would've taken a couple of hours to manually correct them I believe. Line 2619, as mentioned before, was actually part of page 4, would you still like me to go and correct it? Many different missing templates for the remainder of the second page, but I placed in the ones I could find. I left comments on everything I corrected or could not correct.

**Comment by skylartheswimmer** [comment]
I uploaded the first deliverable, but im not sure if this was the correct place to do so? but this is it. thank you!

**Comment by whanley** [comment]
Robert, your deliverable file needs a different name. It's explained here: https://dig-eg-gaz.github.io/how-to/digitization/tei-xml-instructions/#2-create-an-xml-file. Resubmit when it's renamed.

If you don't understand the verification assignment, ask. About your comment "Could not bring myself to type out the following 4 charts, it was very time consuming": to be clear, the expectation is that you correct the whole of the file. You don't have to type out the charts. You have to correct them. This work is time consuming, but if you do it correctly (for instance by using templates and the author mode), you can get it done.

**Comment by skylartheswimmer** [comment]
Renamed deliverable 2 to the date

**Comment by huoyanzhizhou** [comment]
Please delete deliverable 1 pt 1.xml with a wrong file name. Also, please rename 1907-09-02 to 1907-09-02.xml

**Comment by whanley** [comment]
Hi Robert. You should be submitting just three files:
-  1905-09-12.xml
-  1907-09-02.xml
-  1907-09-03.xml

After moving whatever content you want to submit into these files, delete the files named:
-  deliverable 1 pt 1.xml
-  1907-09-02
-  1907-09-03 full.xml

Then send a new pull request.

**Comment by whanley** [comment]
Looking at the content of your submissions, things look good. Remember to use the feature attribute to identify items you OCR, and to update the contents of tables to reflect the contents of the issues you're digitizing.

**Comment by skylartheswimmer** [comment]
Deleted files previously mentioned

**Comment by whanley** [comment]
Okay, the pull request is clean now in terms of the files it contains.

The contents of the files still need work. Fill in the header of your Monday issue. Your Tuesday issue has an extra page div. Also, you use the same Reuters template twice.

Remember that you can use the Format and Indent function to clarify your workspace.

**Pull request merged**
