### PR TITLE
 p

### PR DESCRIPTION
**Pull request by FlameWo**

### CODE REVIEW

**Comment by whanley** [comment]
Monday issue: 
- line 2186: get rid of `<hi>` tag around Local and General--it contains a lot of attributes that cause trouble. Get rid of all of the `<hi rend="bold">` that follow--they come from OCR pasting maybe?
- put all the local and general stories in one section
- many feature attributes needed. Check this page: https://dig-eg-gaz.github.io/features/

Page 4: Telegrams should all be in one section. same for Sport and Play
Page 5: Put ads inside Cheap Prepaid section
Page 6: OCR the french articles

Tables look pretty good.

Tuesday issue: Many similar things to be addressed.

**Comment by whanley** [comment]
- remove the file  1907-03-18.xml.bak from this pull request
- 1907-03-21 has incorrect dates in header and on first page, and is not a valid document (i.e. no green box).
- also true of 1907-03-19
- where is 1907-03-20?

**Comment by FlameWo** [comment]
The data for Wednesday is on the laptop that is getting repaired, I will
have to wait to work on that one.

**Comment by whanley** [comment]
Okay, thanks for this. Keep them coming.

**Pull request merged**
