### PR TITLE
	Deliverable 3

### PR DESCRIPTION
**Pull request by CarlosRod77**
Missing Page 5,6. Page 4 near completion.

### CODE REVIEW

**Comment by whanley** [comment]
Thanks @CarlosRod77 but there is a problem with this pull request. It contains three files, but it should only contain one. Delete the file 1906-07-16 .xml (with a space in it) and 4.4.jpg from your fork, then send a new pull request.

**Comment by CarlosRod77** [comment]
Im still having a lot of problems with GitHub, are you going to be in your office hours class? 

Carlos Rodriguez 
(305)-409-2605
Cjr15c@my.fsu.edu

**Comment by whanley** [comment]
@CarlosRod77 you can find @znr13 in Strozier today (Thursday Feb 16) at 2:30 and tomorrow (Fr Feb 17) at 11. He can help.

**Comment by CarlosRod77** [comment]
1906-07-16  …
Deleted older files (4.4.jpg) resubmitting correct Deliverable 3

**Pull request closed without merging**
