### PR TITLE
1906-06-25 pg 2&3

### PR DESCRIPTION
**Pull request by willpearce1**

### CODE REVIEW

**Comment by znr13** [comment]
@willpearce1 , I only see page 1 here.

**Comment by willpearce1** [comment]
Hi Zach,

I thought I submitted everything but I don’t really know how to work GitHub very well. How do I resubmit?


Thanks,
Will
On Feb 5, 2017, at 3:38 PM, Zachary Reddick <notifications@github.com<mailto:notifications@github.com>> wrote:


@willpearce1<https://github.com/willpearce1> , I only see page 1 here.

**Comment by znr13** [comment]
It looked like you just uploaded your page one. Make sure that you added your most up to date file and then update the pull request.



Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by whanley** [comment]
@willpearce1 commit your updated xml file to your fork of the content repository, then send another pull request.

**Pull request merged**
