### PR TITLE
pages 1-3

### PR DESCRIPTION
**Pull request by gretchensandorf**

### CODE REVIEW

**Comment by gretchensandorf** [comment]
put pages 1-3 in the same file

**Comment by whanley** [comment]
@gretchensandorf this is good work, but we need to make sure that everything is in one single file. At present this pull request contains four files. Come to office hours with @znr13 or me for help with this.

**Comment by gretchensandorf** [comment]
pages 1-6, monday

**Comment by whanley** [comment]
Closing this pull request, which has been superseded by #364.

**Pull request closed without merging**
