### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by rlw16b**
I found some issues with column breaks and some templates missing. But no significant information was missing.

### CODE REVIEW

**Comment by huoyanzhizhou** [comment]
Good start. Please keep working on these files.

**Comment by whanley** [comment]
Lots to do on deliverable 1. First step: give the file the right name. Reread this: https://dig-eg-gaz.github.io/how-to/digitization/tei-xml-instructions/#2-create-an-xml-file

**Comment by whanley** [comment]
Do you need help? Come and see us in office hours.

**Comment by whanley** [comment]
Closing due to non-response.

**Comment by whanley** [comment]
Actually, waiting to see if you add more changes--get in touch if you need help.

**Pull request merged**
