### PR TITLE
derivable 3

### PR DESCRIPTION
**Pull request by samisquires**
Updated

### CODE REVIEW

**Comment by whanley** [comment]
Most items in place for deliverable 3, but you don't seem to have updated the contents of the tables?
Page 6: put ads inside the cheap prepaid ads section.
Page 7: divide into items

**Comment by samisquires** [comment]
Will Hanley,

I updated all but two of them. Two of them were almost new tables out of the templates.


Sami Squires

________________________________

**Comment by whanley** [comment]
Okay, can you deal with pages 6 and 7?

**Comment by whanley** [comment]
Great! Complete.

**Pull request merged**
