### PR TITLE
Deliverable 4

### PR DESCRIPTION
**Pull request by ley06**
Still editing and trying to understand OCR instead of typing text - not quite finished yet

### CODE REVIEW

**Comment by whanley** [comment]
Okay, let me know if I can help.

Please update the date in the header of this new file.

**Comment by whanley** [comment]
Header of Tuesday file says it's Monday! (line 26). Looking forward to the rest of the pages of Tues and Weds

**Comment by whanley** [comment]
Thanks--hope OCR is working?

**Comment by whanley** [comment]
Tuesday issue:
Page 2:
- line 1633 start a new div
Page 3:
- local section: divide into items
- line 1798: this is not a wire section (not telegram reports of international news). Make each story its own div. same for next columns.
Page 4:
- tables look good
Page 5:
- the sections on this page are better (this is where the wire section is). But prepaid ads is inside sport and play

Wednesday:
- some similar issues

Thursday: 
- pages to be completed

**Comment by ley06** [comment]
I corrected page 3 but I'm not sure if its right

**Comment by ley06** [comment]
I also corrected page 3 and eliminated the unnecessary wire, but Im still not sure if its right (Wednesday issue)

**Comment by whanley** [comment]
@ley06 these are generally good but there are still some problems. Probably the best thing is if we sit down and work on them together in office hours.

**Pull request merged**
