### PR TITLE
Pages 4 through 6 are complete. some advertisement templates are needed

### PR DESCRIPTION
**Pull request by jjp15f**
though. Thank you

### CODE REVIEW

**Comment by jjp15f** [comment]
Pages 4 through 6 are complete. some advertisement templates are needed though. Thank you.

**Comment by jjp15f** [comment]
Actually, something messed up with submission, they are finished but i am trying to figure it out now.

**Comment by jjp15f** [comment]
Everything should be correct now, sorry for the confusion.

**Comment by whanley** [comment]
Great!

**Pull request merged**
