### PR TITLE
Create 1907-09-09

### PR DESCRIPTION
**Pull request by esk19b**

### CODE REVIEW

**Comment by whanley** [comment]
Thanks Aaron. Where you've written "no template," what is the source of the advert text? The closest similar ad?

**Comment by esk19b** [comment]
Everything that did not have a clear template that I could use (which I have marked with "no template"), I just wrote by hand. Is that fine?

**Comment by whanley** [comment]
Looks good! At line 5114, use a `</div>` to close page 4 before you start page 5. Keep working to complete the tables.

**Comment by whanley** [comment]
This is great work. Deliverables 1-3 complete, Deliverable 4 is still missing page 6.

There is one problem, however, throughout both issues. You are not using the feature attribute correctly. As an example, telegrams should be tagged `<div type="section" feature="wire>` instead of `<div type="feature">`. Features are specified here: https://dig-eg-gaz.github.io/contents/features/

One more thing: on page 3 of your Monday issue, you make some columns into sections. Please fix this--you do it correctly elsewhere.

**Pull request merged**
