### PR TITLE
Update 1905-10-16.xml

### PR DESCRIPTION
**Pull request by Samuel102014**
I was honestly unsure about whether or not I submitted this correctly. As well I was having issues with oxygen. Please let me know if it turned out correct

### CODE REVIEW

**Comment by huoyanzhizhou** [comment]
Your submission seems to be fine. But could you check the measures, texts, features, and tables more and correct some of them?

**Comment by whanley** [comment]
Your submission was successful, but the content is not done. First of all, don't replace the original editor's name with your own--just add yours on the next line. Second, please do the verification of the xml file against the page images.

**Comment by whanley** [comment]
I made some comments in this pull request -- https://github.com/dig-eg-gaz/content/pull/923

**Comment by whanley** [comment]
I think you are having some problems with pull requests. Please check in with me or Weber.

**Pull request closed without merging**
