### PR TITLE
Page 2-3

### PR DESCRIPTION
**Pull request by cgreco1**
Page 3 is still a work in progress.  My OCR is having a lot of trouble with it.  You keep closing my requests, this is just the file by itself, I'm very confused?  Is there more than one file associated with this request?

### CODE REVIEW

**Comment by whanley** [comment]
Yes @cgreco1 , there are three files associated with this request. Delete 1906-01-15-p1.xml and  1906-01-15-p2:3.xml from your fork of the repository, then send the pull request with only 1906-01-15.xml.

**Comment by cgreco1** [comment]
I believe I properly deleted the files associated with the request, and sent a normal pull request to the main branch.

________________________________

**Comment by whanley** [comment]
We're getting closer @cgreco1, but still not there. Check https://github.com/dig-eg-gaz/content/pull/294/files, which shows that you're deleting 1906-01-15-p1.xml but not adding 1906-01-15.xml. Hope next time is the charm!

**Comment by whanley** [comment]
I'm closing this pull request because I think you have everything right in the pull request you sent subsequently. This should avoid entering the misnamed file into the workflow.

**Pull request closed without merging**
