### PR TITLE
January 21st Assignment

### PR DESCRIPTION
**Pull request by MillyW19**
submitted?

### CODE REVIEW

**Comment by whanley** [comment]
Wonderful work--but still things to be done. Some of the tables on pages 4 and 6 do not correspond to your issue. Material like the Passenger List on page 4 could be OCRed.

**Comment by whanley** [comment]
Please remove the file called My Own Issue1.xml and send a new pull request.

**Comment by huoyanzhizhou** [comment]
Please delete My Own Issue1.xml, the wrong file.

**Comment by whanley** [comment]
This is very fine work, Milly.

There are a few things to do for completion. 
- don't use div type="article". Use "item" or "section" (if it's a larger section containing items).
- Use features
- check all of your date attributes. Find them by searching `//@when`--this will show you what needs to be updated
- there may be some other things. I'll let you know.
- finally, please complete issue verification, per earlier instructions.

**Comment by whanley** [comment]
I deleted the problem file (My Own Issue).

**Comment by huoyanzhizhou** [comment]
Overall good work. Please check these files. @whanley

**Comment by whanley** [comment]
I'm going to merge these changes, but they still need some verification before I call them complete. 

The issue verification file still needs the specified changes made to it.

**Comment by whanley** [comment]
Okay, I'll call these deliverables complete. Great work!

**Pull request merged**
