### PR TITLE
Verification

### PR DESCRIPTION
**Pull request by robmcghee**
Homework due January 21, 11:59pm.

### CODE REVIEW

**Comment by huoyanzhizhou** [comment]
It seems that you did not correct many things... Do you find wrong dates, measures, texts, or features?

**Comment by whanley** [comment]
There are no changes. Please inform.

**Comment by robmcghee** [comment]
There were few issues with the original XML file. All of the dates, prices, etc were accurate. There were a few missing sections, which I added in comments for, but that was it.

**Comment by whanley** [comment]
Line 1741 is not the headline of a div--check the original.

On page 4, these items are missing and need OCR:

```
 <div type="item">
                    <head>LE BILAN DES SUCRERIES</head>
                </div>
                <div type="section" xml:lang="fr" feature="bulletinBourse">
                    <head>BULLETIN DE LA BOURSE</head>
                </div>
```

On page 5, ads should be _inside_ the cheap prepaid adverts section div.

On page 6, I see this:

```
    <div type="item">
                    <head>RESUME DE LA SITUATION COTONNIERE</head>
                </div>
                <div type="item">
                    <head>NOLIS</head>
                </div>
                <div type="item">
                    <head>DELTA LIGHT RAILWAY Ltd.</head>
                </div>
                <div type="item">
                    <head>EGYPTIAN MARKETS, LIMITED.</head>
                </div>
```
and later
```
  <div type="item">
                    <head>ARRIVAGES A MINET-EL-BASSAL</head>
                </div>
                <div type="item">
                    <head>COALS</head>
                </div>
```


Please fill in with templates and details.

**Pull request closed without merging**
