### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by carolinebanks**
I didn't see a lot of problems, but I added a bunch of datelines and distinguished headings that were previously just called <p>

### CODE REVIEW

**Comment by whanley** [comment]
On page 1, many of the when= attributes in the date tags do not correspond to the date given.

There are lots of hanging hyphens in the text, for example on page 5.

Calendar of Coming events and perhaps other tables do not reflect the contents of the issue itself.

**Comment by huoyanzhizhou** [comment]
Please check your file names and delete the incorrect files.

**Comment by whanley** [comment]
Hi Carolyn, good work on these deliverables. I've deleted the misnamed files, and what's left is correctly named.

The first thing to work on is the page structure. Look at this: https://dig-eg-gaz.github.io/how-to/digitization/polished-tei-instructions/. The June 9 issue is good, until partway through page 6. The June 8 issue has problems, many caused by coding like this `<div type="page" n="6"/>`, which closes your page before you open it--get rid of the slash! 

I also notice that you have a lot of bold text left over from OCR--please remove.

Also, clean up the header of these files.

One more thing: don't use a "masthead" at the beginning of each page. Just a `<head>` is enough.

Clean these up and I'll look again.

**Comment by whanley** [comment]
Verification is looking quite good, though there are still problems. For example, Eastern Telegram table is not updated. Nouveau Remede ad is missing on page 6. 

One big one: run the `//@when` query on this file, and you'll find a lot of attributes that need to be updated.

**Comment by whanley** [comment]
Almost there!

**Pull request merged**
