### PR TITLE
1905-09-01.xml

### PR DESCRIPTION
**Pull request by Johnw321**
I had an issue finding the error in the div command at the end. Also, the text is corrupted/unedited from p4 down. Other pages seem to be accurate.

### CODE REVIEW

**Comment by huoyanzhizhou** [comment]
It seems that you did not submit a valid file. Please check with Dr. Hanley or me (Weber) on next class. 
Also, please do not change the file name, since your file is going to compare with and replace the old file.

**Comment by whanley** [comment]
The file name looks okay. There are strange things on pages 4 and 6, you're right. What he's done is to OCR material that should be in templates, then put that material in a comment field. Please put the templates in place for these. You can leave the commented OCR stuff for now.

Check to see if you can figure out what other things he might have done.

**Comment by whanley** [comment]
Keep working on the verification.

For Deliverable 1, there is a problem with the file you submitted with the name 1906-08-16.xml. It is not a valid xml file. See if you can fix it, or check with us.

**Comment by whanley** [comment]
Anything to report? Stop by office hours for help if you like...

**Comment by Johnw321** [comment]
Prof. Hanley,

I apologize for getting so behind on this. I’ve had a rough couple of weeks but plan on taking the week to hop back on the horse and catch up. I apologize again.

Thanks,

John Justice

(407) 310-2817
Johnwesley.justice@gmail.com


On Feb 24, 2020, at 5:51 PM, Will Hanley <notifications@github.com> wrote:

﻿

Anything to report? Stop by office hours for help if you like...

**Comment by huoyanzhizhou** [comment]
Good start, please continue working on deliverable and we still got time for them. Remember to ask questions, and we are here to help.

**Comment by whanley** [comment]
I'll echo Weber--keep at it, and videoconference when you need help.

**Comment by whanley** [comment]
Closing pull request at end of semester.

**Pull request closed without merging**
