### PR TITLE
Deliverables 1, 2, 3, 4, and issue verification

### PR DESCRIPTION
**Pull request by tw19e**
I added datelines, missing ads, and fixed some typos.

### CODE REVIEW

**Comment by whanley** [comment]
Nice work. If you are on top of OCR, can you go ahead and supply the missing material that you've noted, especially on pages 4 and 5?

**Comment by huoyanzhizhou** [comment]
Lots of good work. But there is a conflict going on. @whanley

**Comment by whanley** [comment]
I'm going to merge this pull request, which is really good work. Full completion grades pending a bit more study. One thing that has to be done: run a `//@when` query and you'll find a few attributes to update. Some of your `@feature` attributes are lacking as well.

**Comment by whanley** [comment]
There are issues with verification--page 6, for example: Cloture de la bourse, this stuff:
```
 <div type="item">
                    <head>Administration des Douanes AVIS</head>
                </div>
                <div type="item">
                    <head>CREDIT FONCIER EGYPTIEN</head>
                </div>
```
Make sure you go through each page carefully.

**Pull request merged**
