### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by kml18f**
Wasn't finding that many things wrong.

### CODE REVIEW

**Comment by huoyanzhizhou** [comment]
Measures in Nile Gauge Readings (Page 4) are not updated.

**Comment by whanley** [comment]
You could add datelines on page 3. 

Primes des Contracts template, line 3100?

Page 6 needs many templates.

**Comment by whanley** [comment]
The end of your file has a whole bunch of empty pages!

**Comment by huoyanzhizhou** [comment]
In your 1906-03-24 file, everything after first page is inside the first page div, and every after second page is inside the second page div... Please make all page div in the same level. Check your outline window to correct it. See https://dig-eg-gaz.github.io/how-to/digitization/polished-tei-instructions/ for further instruction. Also, please check your features, see https://dig-eg-gaz.github.io/contents/features/

**Comment by whanley** [comment]
Good talking to you yesterday--I look forward to seeing updates of these deliverables.

**Comment by huoyanzhizhou** [comment]
Some features are wrong. For example, Local and General should be "local" rather than "wire". See https://dig-eg-gaz.github.io/contents/features/ 
Also, please check and update the measures in your tables.

**Pull request merged**
