### PR TITLE
1908-01-07.xml

### PR DESCRIPTION
**Pull request by vg19-fsu**

### CODE REVIEW

**Comment by huoyanzhizhou** [comment]
Some files in your pull request are not needed, please delete the extra files. The measures and dates are not updated in Wednesday file, including the issue date (line 26). Also, please use features and create sections. For example, the local and general should be section with a feature of "local", and you should put the small items under the bigger sections.

**Comment by whanley** [comment]
Specifically, the files to delete are  `dig-eg-gaz-code-templates.xml` and ` 1908-01-06.xml.txt`.

Generally you are doing very good work and the 4 issues are almost there. Please tidy them up a bit, both in format (including using feature attributes) and by updating the templates. This tutorial should help a bit: https://dig-eg-gaz.github.io/how-to/digitization/polished-tei-instructions/

Don't hesitate to stop by office hours if you need help doing the last tidying.

Keep at it! I'm excited to merge these into the master repo.

**Comment by huoyanzhizhou** [comment]
Any updates?

**Comment by whanley** [comment]
Vanessa, I'm going to merge this pull request because it contains lots of great material for your Monday to Friday issues. However, each file needs some tidying. Maybe we can sit down next week and look at what remains to be done. You are almost there!

**Pull request merged**
