### PR TITLE
Deliverable 5

### PR DESCRIPTION
**Pull request by dlg16**

### CODE REVIEW

**Comment by whanley** [comment]
Lots of good stuff here. It looks like OCR isn't treating you too well. Have you tried Finereader instead of Tesseract?

Try putting all of the content of each page in a `<div type="page">` tag. It looks like you are making each column into its own item, which is not necessary. Let me help you with formatting in class or office hours.

**Comment by dlg16** [comment]
Made corrections to Monday Issue.
Tuesday issue not yet fully complete.

**Comment by dlg16** [comment]
Mon, Tue, Wed - complete
Thu - missing issue, I've emailed you a reminder

**Comment by whanley** [comment]
Great job. Some correction work remains to be done, obviously, especially on Monday. And there are various ads and templates not entirely updated. Look for these with a `//@when` query. But well done in general! Nice careful structure to your files.

**Pull request merged**
