### PR TITLE
Monday p.4-6

### PR DESCRIPTION
**Pull request by cwiklata**
Pages 4-6 complete, just a few templates needed to complete them. I'm working on pages 7-8 as quickly as I can.

### CODE REVIEW

**Comment by whanley** [comment]
There is a problem with the filename associated with this pull request @cwiklata -- there is a space before the .xml extension. Please fix the filename and send again.

**Comment by cwiklata** [comment]
Hi, I fixed the error then tried to re-upload my file, however I think I
have somehow managed to create a pull request for 60-something various
items rather than just my own. I genuinely don't know how that happened,
I'll talk to you after class tomorrow to see if I can cancel that and
figure out how to correctly submit my single pull-request. I'm sorry if
this complicates your end of things.
Taylor Cwikla

**Comment by whanley** [comment]
Hi @cwiklata -- I'm not seeing the 60 files, which is good. But I am seeing two files. Can you delete the file with a space in the name from your fork, then send the same pull request again? That should leave just one file.

**Comment by whanley** [comment]
Great job!

**Pull request merged**
