### PR TITLE
1905-09-21

### PR DESCRIPTION
**Pull request by jakemcleod1999**
Editing the 09/21/1905 issue of The Egyptian Gazette.

### CODE REVIEW

**Comment by huoyanzhizhou** [comment]
It seems that this file is not using templates of advertisements. Please check https://dig-eg-gaz.github.io/contents/advertisements/ to see if you can replace the ads with templates.

**Comment by whanley** [comment]
Please add missing text where your comments show it's missing. You should be able to find it in templates.

**Comment by whanley** [comment]
I'm confused--were you aiming to fix up your verification issue?

For deliverables 1 and 2, all I see are ad templates. Where is the rest?

**Comment by jakemcleod1999** [comment]
I looked at the directions for "How to perform structural markup in TEI-XML" on the course website. I followed those directions for the deliverables. Was this not what I was supposed to do?

**Comment by huoyanzhizhou** [comment]
Did you read the OCR instructions on our website?

**Comment by jakemcleod1999** [comment]
Is this the link to the proper instructions: https://dig-eg-gaz.github.io/how-to/digitization/ocr-instructions/

**Comment by whanley** [comment]
Hi Jake. All that these issues contain is ads. They also need to contain OCRed material (articles) and financial tables. Read the tutorials, and ask us for help.

**Comment by whanley** [comment]
Closing at end of semester

**Pull request closed without merging**
