### PR TITLE
adverts added and page 6 completed

### PR DESCRIPTION
**Pull request by selinanevin**

### CODE REVIEW

**Comment by whanley** [comment]
Do the contents of the tables on page 6 correspond to your issue? I see some discrepancies.

**Comment by selinanevin** [comment]
I believe I just added the tables. Should I go back and make sure the values match the image?

**Comment by whanley** [comment]
> I believe I just added the tables. Should I go back and make sure the values match the image?

Yes

**Comment by whanley** [comment]
Lots of great work for deliverables 1 and 2. As a next step, look at this: https://dig-eg-gaz.github.io/how-to/digitization/polished-tei-instructions/#1-get-the-page-hierarchy-right

**Comment by whanley** [comment]
Any updates?

**Comment by huoyanzhizhou** [comment]
For features that involve many consistent small articles, please create a div type="section" and put small items inside that. In this way, you can only use a feature one time in a file. 
Please check the measures and update them. For example, the data in REUTER'S TELEGRAMS (1907-08-16) is not updated yet.

**Pull request merged**
