### PR TITLE
1907-08-19-p1 

### PR DESCRIPTION
**Pull request by DDorsey-bit**
This is the unfinished products

### CODE REVIEW

**Comment by huoyanzhizhou** [comment]
Please check your edition date, the orange values does not match the black words.

**Comment by whanley** [comment]
Thanks Mali. As Weber says, there's a problem with your date, which is giving an error message on Oxygen. Get a green box before submitting.

**Comment by DDorsey-bit** [comment]
Greetings,

I will fix this issue very soon.

Thanks,
Mali
________________________________

**Comment by whanley** [comment]
This looks good--but add more content please!

**Comment by whanley** [comment]
Any updates?

**Comment by DDorsey-bit** [comment]
Greetings Mr. Hanley,

I have been making changes to this article but my oxygen xml file did not update and I lost all of my data. I was able to encode my first page again but I wasn't able to correct it for my day. If possible I would like to schedule an office hour appointment.

Best,
Damamli
________________________________

**Comment by whanley** [comment]
Sounds good--send me an email at whanley@fsu.edu and we'll find a time.

**Comment by huoyanzhizhou** [comment]
Any news?

**Pull request merged**
